version: '2'
services:
  droppy:
    container_name: droppy
    image: silverwind/droppy
    ports:
      - '0.0.0.0:8083:8989'
    volumes:
      - ./config:/config
      - ./data:/files
    restart: unless-stopped
