version: '3.3'
services:
    henrywhitaker3_speedtest:
        container_name: henrywhitaker3_speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /usr/local/henrywhitaker3_speedtest:/config
        environment:
            - TZ=
            - PGID=
            - PUID=
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

# Attach to existing non-default network
networks:
  default:
    external:
      name: linuxserver-nginx_default
