---
version: "2.1"
services:
  pwndrop:
    image: ghcr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - SECRET_PATH=/pwndrop
    volumes:
      - /usr/local/pwndrop/config:/config
    ports:
      - 8080:8080
    restart: unless-stopped
#    restart: always